app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signIn, name='login'),
    path('login/error', views.loginError, name='login_error'),
    path('logout/', views.logOut, name='logout'),
    path('register/', views.signUp, name='register'),
    path('register/success', views.signUpSuccess, name='register_success'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/add-restaurant/', views.addRestaurant, name='add_restaurant'),
    path('dashboard/restaurant/<slug:slug>/', views.displayRestaurant, name='view_restaurant'),
    path('dashboard/restaurant/<slug:slug>/add-dish/', views.addDish, name='add_dish'),
    path('dashboard/restaurants/', views.displayRestaurants, name='display_restaurants'),
    path('dashboard/restaurants/<slug:slug>/', views.makeOrder, name='make_order'),
    path('dashboard/order/', views.viewPlacedOrder, name='order'),
    path('dashboard/order/<int:order_id>/', views.displayOrder, name='display_order'),
    path('dashboard/order/<int:order_id>/review', views.displayReview, name='display_review'),
]

smarteats/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),

]

app/models.py
from django.db import models, reset_queries
from django.contrib.auth.models import AbstractUser, User
from django.conf import settings
from django.contrib.auth.models import Group
from django.utils.text import slugify


CUISINE_CATEGORY = [
    ('asian', 'Azjatycka'),
    ('european', 'Europejska', ),
    ('italian', 'Włoska'),
    ('japan', 'Japońska'),
]


class CustomUser(AbstractUser):
    USER_ROLE = [
        ('customer', 'klient', ),
        ('restaurant', 'restaurator'),
        ('supplier', 'dostawca'),
    ]
    user_role = models.CharField(max_length=30, choices=USER_ROLE)

    def get_role(self):
        return self.user_role


class Restaurant(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=30, choices=CUISINE_CATEGORY)
    address_city = models.CharField(max_length=30)
    address_street = models.CharField(max_length=30)
    address_postalcode = models.CharField(max_length=6)
    description = models.CharField(max_length=200)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    slug = models.SlugField(max_length=255, unique=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            val = self.slug
        return super(Restaurant, self).save(*args, **kwargs)

class Supplier(models.Model):
    name = models.CharField(max_length=50)


class Dish(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField(max_length=6)
    description = models.CharField(max_length=100)
    ingredients = models.CharField(max_length=150, null=True)
    alergens = models.CharField(max_length=50)
    restaurant_id = models.ForeignKey('Restaurant', null=True, on_delete=models.DO_NOTHING)

ORDER_STATUS = [
    ('awaiting', 'Oczekujące na zatwierdzenie'),
    ('accepted_restaurant', 'Zatwierdzone przez restaurację', ),
    ('in_progress', 'Realizowane'),
    ('finished', 'Zakończone'),
    ('aborted', 'Anulowane'),
]

ACCEPTANCE_DECISION = [
    ('awaiting', 'Oczekujące'),
    ('accepted', 'Zaakceptowane'),
    ('aborted', 'Odrzucone'),
]

class Order(models.Model):
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS, default='awaiting')
    restaurant_acceptance = models.CharField(max_length=30, choices=ACCEPTANCE_DECISION, default='awaiting')
    supplier_acceptance = models.CharField(max_length=30, choices=ACCEPTANCE_DECISION, default='awaiting')
    ordered_user = models.ForeignKey('CustomUser', null=True, related_name="ordered_user", on_delete=models.DO_NOTHING)
    delivery_address = models.CharField(max_length=60, null=True)
    restaurant = models.ForeignKey('Restaurant', null=True, on_delete=models.DO_NOTHING)
    supplier = models.ForeignKey('CustomUser', null=True, related_name='supplier', on_delete=models.DO_NOTHING)
    created_on = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    items = models.ManyToManyField('Dish', related_name='order', blank=True)
    review = models.ForeignKey('Review', null=True, on_delete=models.DO_NOTHING)


class ChatGroup(Group):
    description = models.TextField(blank=True)
    mute_notifications = models.BooleanField(default=False)
    icon = models.ImageField(help_text="Group icon", blank=True, upload_to="chartgroup")
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('dashboard/order:room', args=[str(self.id)])

class Message(models.Model):
    user = models.CharField(max_length=250)
    room = models.CharField(max_length=250)
    date = models.CharField(max_length=250)
    message = models.TextField()
    objects = models.Manager

    def __str__(self):
        return self.user + ' ' + self.room + ' ' + self.date + ' ' + self.message

REVIEW_STATUS = [
    ('awaiting', 'Oczekująca na wystawienie'),
    ('issued', 'Wystawiona'),
]

REVIEW_RATE = [
    ('0', 'Wybierz ocenę'),
    ('1', 'Bardzo źle'),
    ('2', 'Źle'),
    ('3', 'Dostatecznie'),
    ('4', 'Dobrze'),
    ('5', 'Bardzo dobrze'),
]


class Review(models.Model):
    #order = models.ForeignKey('Order', null=True, on_delete=models.DO_NOTHING)
    review_status = models.CharField(max_length=30, choices=REVIEW_STATUS, default='awaiting')
    restaurant_rate = models.CharField(max_length=30, choices=REVIEW_RATE, default='')
    restaurant_rate_desc = models.CharField(max_length=200)
    supplier_rate = models.CharField(max_length=30, choices=REVIEW_RATE, default='')
    supplier_rate_desc = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

app/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SmartEats</title>
  <meta name="description" content="SmartEats">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  {% block content %}
  {% endblock %}
  <script src="js/app.js"></script>
</body>
</html>

app/templates/dashboard_restaurant.html
{% extends 'dashboard.html' %}

<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="css/styles.css?v=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  {% block content %}
      <div id="dashboard-restaurants-container">
        <div id="dashboard-restaurants">
            <h3>Twoje restauracje</h3>
            <h6>Określ czy Twoja restauracja jest w stanie zrealizować dane zamówienie</h6>
            <table class="table-restaurants">
                <tr>
                    <th>Nazwa</th>
                    <th style="width:200px;">Rodzaj kuchni</th>
                    <th>Adres</th>
                </tr>
                {% for restaurant in restaurants %}
                <tr>
                    <td><a href="./restaurant/{{ restaurant.slug }}">{{ restaurant.name }}</a></td>
                    <td>{{ restaurant.get_category_display }}</td>
                    <td>{{ restaurant.address_street }}, {{ restaurant.address_city }}, {{ restaurant.address_postalcode}},</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <a class="reg-log-button" href="./add-restaurant/"><button>Dodaj restaurację</button></a>
      </div>
      <div id="dashboard-awaiting-orders-container">
        <div id="dashboard-awaiting-orders">
            <h3>Zamówienia oczekujące na zatwierdzenie</h3>
            <h6>Określ czy Twoja restauracja jest w stanie zrealizować dane zamówienie</h6>
            <table class="table-awaiting-orders">
                <tr>
                    <th>ID</th>
                    <th>Status restauracji</th>
                    <th>Status ogólny</th>
                    <th>Restauracja</th>
                    <th>Data zamówienia</th>
                    <th>Zamawiający</th>
                    <th>Kwota</th>
                </tr>
                {% for order in orders|dictsort:"order_status" %}
                {% if order.order_status == 'awaiting' %}
                <tr>
                    <td><a href="./order/{{ order.id }}">{{ order.id }}</a></td>
                    <td>{{ order.get_restaurant_acceptance_display}}</td>
                    {% if order.order_status == 'awaiting' and order.restaurant_acceptance == 'accepted'%}
                    <td>Oczekujące na dostawcę</td>
                    {% else %}
                    <td>Oczekujące na zatwierdzenie</td>
                    {% endif %}
                    <td>{{ order.restaurant.name}}</td>
                    <td>{{ order.created_on|date:'d-m-Y H:i:s' }}</td>
                    <td>{{ order.ordered_user.first_name }} {{ order.ordered_user.last_name }}</td>
                    <td>{{ order.price }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>
        </div>
      </div>

     <div id="dashboard-orders-container">
        <div id="dashboard-orders">
            <h3>Zamówienia</h3>
            <table class="table-dashboard-orders">
                <tr>
                    <th>ID</th>
                    <th>Status</th>
                    <th>Restauracja</th>
                    <th>Data zamówienia</th>
                    <th>Zamawiający</th>
                    <th>Kwota</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td><a href="./order/{{ order.id }}">{{ order.id }}</a></td>
                    <td>{{ order.get_order_status_display}}</td>
                    <td>{{ order.restaurant.name}}</td>
                    <td>{{ order.created_on|date:'d-m-Y H:i:s' }}</td>
                    <td>{{ order.ordered_user.first_name }} {{ order.ordered_user.last_name }}</td>
                    <td>{{ order.price }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
     </div>
    {% endblock %}
  <script src="js/scripts.js"></script>
</body>
</html>

app/templates/order_details_restaurant.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
<div id="dashboard-header">
    <h1>Witaj, {{ user_name }}! Twoja rola w systemie to {{ user.get_user_role_display }}.</h1>
    <a class="reg-log-button" href="http://127.0.0.1:8000/logout/"><button>Wyloguj się</button></a>
</div>
<div id="main-content">
    <h2>Zamówienie numer {{ order.id }}</h2>
    <div class="details">
  <h4>Adres dostawy: {{ order.delivery_address }}</h4>
  <h4>Data i godzina zamówienia {{ order.created_on|date:'d-m-Y H:i:s' }}</h4>
  <h4>Kwota zamówienia {{ order.price }}</h4>
    </div>

    <div id="awaiting-orders-container">
        <h4 style="text-align: center; padding-top: 10px;">Twoje zamówienie</h4>
        <table class="table-awaiting-orders">
            <tr>
                <th>Nazwa dania</th>
                <th>Cena</th>
            </tr>
            {% for dish in dishes %}
            <tr>
                <td>{{ dish.name }}</td>
                <td>{{ dish.price }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div id="order-details">
        <h4>Status dostawcy: {{ order.get_supplier_acceptance_display}}</h4>
        <h4>Twój status: {{ order.get_restaurant_acceptance_display}}</h4>
        </br>
        {% if order.restaurant_acceptance == 'awaiting' %}
            <div id="div-awaiting-confirmation-order">
                <form method="POST">
                {% csrf_token %}
                <a  class="reg-log-button"><button>Zatwierdź zamówienie</button></a>
                </br>
                </br>
                </form>
            <a class="reg-log-button" href="/dashboard/"><button>Powrót</button></a>
            </div>
        {% elif order.restaurant_acceptance == 'accepted' and order.supplier_acceptance == 'accepted' %}
            <h5>Zamówienie zostało zaakceptowane przez dostawcę. Możesz rozpocząć jego przygotowanie.</h5>
            </br>
            <h5>W razie potrzeby kontatku z klientem lub dostawcą, wyślij wiadomość poniżej</h5>
            </br>
            </br>
            <a class="reg-log-button" href="/dashboard/"><button>Powrót</button></a>
        {% elif order.restaurant_acceptance == 'accepted' %}
            <div id="div-confirmed-order">
                <h5>Dziękujemy za zatwierdzenie zamówienia.</h5>
                <h5>Jego realizację będziesz mógł rozpocząć gdy dostawca je zatwierdzi.</h5>
                </br>
                </br>
                <a class="reg-log-button" href="/dashboard/"><button>Powrót</button></a>
            </div>
        {% endif %}
    </div>
  {% if order.restaurant_acceptance != 'accepted' %}
      <div id="chat-container">
        <div id="chat-output"><h2 style="text-align: center">Czat będzie dostępny po zatwierdzeniu przez Ciebie zamówienia</h2></div>
    </div>
    {% else %}
<script>
            var div = document.getElementById("chat-container");
            div.style.display = "none";
        </script>
<div id="chat-container">
            <div id="chat-output"></div>
            {% if is_reviewed != True %}
              <input id="chat-input" type="text" size="50"><br>
              <input id="chat-submit" type="button" value="Wyślij">
            {% endif %}
        </div>
</div>
{% endif %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script>
    var url = 'ws://' + window.location.host + '/ws/dashboard/order/' + "{{ order.id }}" + '/';
    console.log(url);
    var chatSocket = new WebSocket(url);
    var $chat = $('#chat-output');
    var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true };
    
    let system_messages = [];
    "{% for mess in messages %}"
    var x = "{{ mess }}".split(' ');
    if ( x[0] === 'SYSTEM' ) {
      let msg = "{{ mess }}";
      system_messages.push(msg);
    } 
    joined_message = '';
      for (let i = 3; i < x.length; i++) {
        joined_message = joined_message + ' ' + x[i];
    }

    if (x[0] == "{{ user.username }}") {
      date = Date.parse(x[2])
      var datetime = moment(date).format("DD-MM-YYYY HH:mm:ss")
      $chat.append('<div class="message-me">' +
        '<div class="message-me-content">' +
        '<strong>' + "Ja" + '</strong> ' +
        '<span class="date">' + datetime + '</span><br>' +
        '<p class="message">' + joined_message + '</p>' +
        '</div>' +
        '</div>');
    }
    else {
      let nickname = '';
      if (x[0] == "{{ supplier_name }}") {
        nickname = 'Dostawca';
      }
      else if (x[0] == "{{ customer_name }}") {
        nickname = 'Zamawiający';
      }
      else if (x[0] == 'SYSTEM') {
              nickname = 'SYSTEM';
      }

      date = Date.parse(x[2]);
      var datetime = moment(date).format("DD-MM-YYYY HH:mm:ss")
      if (x[0] == 'SYSTEM') {
              datetime = '';
      }

      $chat.append('<div class="message-other">' +
        '<div class="message-other-content">' +
        '<strong>' + nickname + '</strong> ' +
        '<span class="date">' + datetime + '</span><br>' +
        '<p class="message">' + joined_message + '</p>' +
        '</div>' +
        '</div>');
    }
    $chat.scrollTop($chat[0].scrollHeight);
    "{% endfor %}"

    let restaurant_acceptance_msg = false;
    chatSocket.addEventListener('open', function (event) {
      if (chatSocket.readyState === WebSocket.OPEN) {
        if (system_messages.length > 0) {
          for (index = 0; index < system_messages.length; index++) {
              if (system_messages[index].includes("Zamówienie zostało zatwierdzone przez restaurację")) {
                restaurant_acceptance_msg = true;
                break;
            }
          }
          let restaurant_accepted = '{{ order.restaurant_acceptance }}';
          if (restaurant_acceptance_msg == false && restaurant_accepted == 'accepted') {
            var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true};
            var datetime = moment().format("DD-MM-YYYY HH:mm:ss")
            var name = 'SYSTEM';
            var message = 'SYSTEM@@@Zamówienie zostało zatwierdzone przez restaurację o godzinie: ' + datetime.substring(10);
            chatSocket.send(JSON.stringify({'message': message}));
            location.reload();
          }
        }
      }
    });

    chatSocket.onmessage = function (e) {
      const data = JSON.parse(e.data);
      var message = data.message;
      var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true };
      var datetime = moment(data.datetime).format("DD-MM-YYYY HH:mm:ss")
      var isMe = data.user === '{{ request.user }}';
      var source = isMe ? 'me' : 'other';
      var name = isMe ? 'Ja' : data.user;
      
      if (data.user == 'SYSTEM') {
          name = 'SYSTEM';
          datetime = '';
      }

      $chat.append('<div class="message-' + source + '">' +
        '<div class="message-' + source + '-content">' +
        '<strong>' + name + '</strong> ' +
        '<span class="date">' + datetime + '</span><br>' +
        '<p class="message">' + message + '</p>' +
        '</div>' +
        '</div>');
      $chat.scrollTop($chat[0].scrollHeight);
    };

    chatSocket.onclose = function (e) {
      console.error('Chat socket closed unexpectedly');
    };

    var $input = $('#chat-input');
    var $submit = $('#chat-submit');

    $submit.click(function () {
      var message = $input.val();
      if (message) {
        chatSocket.send(JSON.stringify({ 'message': message }));
        $input.val('');
        $input.focus();
      }
    });

    $input.focus();
    $input.keyup(function (e) {
      if (e.which === 13) {
        $submit.click();
      }
    });
  </script>

</body>

</html>

app/templates/order_details_supplier.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div id="dashboard-header">
        <h1>Witaj, {{ user_name }}! Twoja rola w systemie to {{ user.get_user_role_display }}.</h1>
        <a class="reg-log-button" href="http://127.0.0.1:8000/logout/"><button>Wyloguj się</button></a>
    </div>
  <div id="main-content">
  <h2>Zamówienie numer {{ order.id }}</h2>
  <div class="details">
  <h4>Status zamówienia: {{ order.get_order_status_display }}</h4>
  <h4>Data i godzina zamówienia: {{ order.created_on|date:'d-m-Y H:i:s' }}</h4>
      <h4>Kwota zamówienia {{ order.price }}</h4>
  </div>
  <div id="awaiting-orders-container">
  <h4>Adres dostawy: {{ order.delivery_address }}</h4>
  <h4>Adres restauracji: 
    {{ order.restaurant.address_street}},
    {{ order.restaurant.address_city }}
    {{ order.restaurant.address_postalcode }}
  </h4>
  <h4>Status restauracji: {{ order.get_restaurant_acceptance_display}}</h4>
  </div>
  <div id="order-details">
    {% if order.supplier_acceptance == 'awaiting' %}
    <div id="div-awaiting-confirmation-order"></div>
    <form method="POST">
      {% csrf_token %}
        <a class="reg-log-button"><button>Zatwierdź zamówienie</button></a>
    </form>
    {% else %}
    <div id="div-confirmed-order">
      <h5>Dziękujemy za zatwierdzenie zamówienia.</h5>
        </br>
      <h5>Możesz rozpocząć realizację zamówienia, udaj się do restauracji po jego odbiór</h5>
    </div>
    {% endif %}
  </br>
  <a class="reg-log-button" href="/dashboard/"><button>Powrót</button></a>
  </div>
  {% if order.restaurant_acceptance != 'accepted' %}
      <div id="chat-container">
        <div id="chat-output"><h2 style="text-align: center">Czat będzie dostępny po zatwierdzeniu zamówienia przez restaurację</h2></div>
    </div>
    {% else %}
<script>
            var div = document.getElementById("chat-container");
            div.style.display = "none";
        </script>
<div id="chat-container">
            <div id="chat-output"></div>
            {% if is_reviewed != True %}
              <input id="chat-input" type="text" size="50"><br>
              <input id="chat-submit" type="button" value="Wyślij">
            {% endif %}
        </div>
</div>
{% endif %}


  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script>
   
    var url = 'ws://' + window.location.host + '/ws/dashboard/order/' + "{{ order.id }}" + '/';
    console.log(url);
    var chatSocket = new WebSocket(url);
    var $chat = $('#chat-output');
    var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true};

    let system_messages = [];
    "{% for mess in messages %}"
        var x = "{{ mess }}".split(' ');
        if ( x[0] === 'SYSTEM' ) {
          let msg = "{{ mess }}";
          system_messages.push(msg);
        } 
        joined_message = '';
          for (let i = 3; i < x.length; i++) {
            joined_message = joined_message + ' ' + x[i];
        }

        if(x[0]=="{{ user.username }}"){
            date = Date.parse(x[2])
            var datetime = moment(date).format("DD-MM-YYYY HH:mm:ss")
            $chat.append('<div class="message-me">' +
                 '<div class="message-me-content">' +
                 '<strong>' + "Ja" + '</strong> ' +
                 '<span class="date">' + datetime + '</span><br>' +
                 '<p class="message">' + joined_message + '</p>' +
                 '</div>' +
                 '</div>');
        }
        else {
            let nickname = '';
            if (x[0] == "{{ customer_name }}") {
              nickname = 'Zamawiający';
            }
            else if (x[0] == "{{ restaurant_owner_name }}") {
              nickname = 'Restaurator';
            }
            else if (x[0] == 'SYSTEM') {
              nickname = 'SYSTEM';
            }

            date = Date.parse(x[2]);
            var datetime = moment(date).format("DD-MM-YYYY HH:mm:ss")
            if (x[0] == 'SYSTEM') {
              datetime = '';
            }

            $chat.append('<div class="message-other">' +
                 '<div class="message-other-content">' +
                 '<strong>' + nickname + '</strong> ' +
                 '<span class="date">' + datetime + '</span><br>' +
                 '<p class="message">' + joined_message + '</p>' +
                 '</div>' +
                 '</div>');
        }
        $chat.scrollTop($chat[0].scrollHeight);
    "{% endfor %}"

    let supplier_acceptance_msg = false;
    chatSocket.addEventListener('open', function (event) {
      if (chatSocket.readyState === WebSocket.OPEN) {
        if (system_messages.length > 0) {
          for (index = 0; index < system_messages.length; index++) {
              if (system_messages[index].includes("Zamówienie zostało zatwierdzone przez dostawcę")) {
                supplier_acceptance_msg = true;
                break;
            }
          }
          let supplier_accepted = '{{ order.supplier_acceptance }}';
          if (supplier_acceptance_msg == false && supplier_accepted == 'accepted') {
            var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true};
            var datetime = moment().format("DD-MM-YYYY HH:mm:ss")
            var name = 'SYSTEM';
            var message = 'SYSTEM@@@Zamówienie zostało zatwierdzone przez dostawcę o godzinie: ' + datetime.substring(10);
            chatSocket.send(JSON.stringify({'message': message}));
            location.reload();
          }
        }
      }
    });

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        var message = data.message;
        var dateOptions = { day: 'numeric', month: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', hour12: true};
        var datetime = moment(data.datetime).format("DD-MM-YYYY HH:mm:ss")
        var isMe = data.user === '{{ request.user }}';
        var source = isMe ? 'me' : 'other';
        var name = isMe ? 'Ja' : data.user;

        if (data.user == 'SYSTEM') {
          name = 'SYSTEM';
          datetime = '';
        }

        $chat.append('<div class="message-' + source + '">' +
                 '<div class="message-' + source + '-content">' + 
                 '<strong>' + name + '</strong> ' +
                 '<span class="date">' + datetime + '</span><br>' +
                 '<p class="message">' + message + '</p>' +
                 '</div>' +
                 '</div>');
        $chat.scrollTop($chat[0].scrollHeight);
        };

    chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
    };

    var $input = $('#chat-input');
    var $submit = $('#chat-submit');

    $submit.click(function() {
        var message = $input.val();
        if(message) {
          chatSocket.send(JSON.stringify({'message': message}));
          $input.val('');
          $input.focus();
        }
    });

    $input.focus();
    $input.keyup(function(e) {
    if (e.which === 13) {
      $submit.click();
    }
  });
</script>

  <script src="js/scripts.js"></script>
</body>
</html>